; =============================================================================
; TITLE    : VARIABLES
; AUTHOR   : Joan Balaguer, Jaume Adrover
; COMMENTS :
; HISTORY  : 20/10/2021
; =============================================================================

MAPADDR 

MAPSEGAD DS.L 1

MAPLEDAD DS.L 1

MAPSWTAD DS.L 1

MAPBUTAD DS.L 1

*~Font name~Courier New~
*~Font size~10~
*~Tab type~1~
*~Tab size~4~
