/* The following code was generated by JFlex 1.7.0 */

/**
 * Copyright (c) 2011-2014 Hossein Hojjat. All rights reserved.
 * 
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 * 
 * * Redistributions of source code must retain the above copyright notice, this
 *   list of conditions and the following disclaimer.
 * 
 * * Redistributions in binary form must reproduce the above copyright notice,
 *   this list of conditions and the following disclaimer in the documentation
 *   and/or other materials provided with the distribution.
 * 
 * * Neither the name of the authors nor the names of their
 *   contributors may be used to endorse or promote products derived from
 *   this software without specific prior written permission.
 * 
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

package lazabs.parser;
import java_cup.runtime.*;
import java.math.BigInteger;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.7.0
 * from the specification file <tt>example.jflex</tt>
 */
public class Lexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  private static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  private static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\3\1\2\1\0\1\3\1\1\22\0\1\3\1\17\2\0"+
    "\1\22\1\21\1\15\1\11\1\32\1\33\1\13\1\4\1\30\1\5"+
    "\1\27\1\12\1\6\11\7\1\14\1\31\1\24\1\25\1\26\1\0"+
    "\1\23\1\40\1\63\2\10\1\42\3\10\1\62\2\10\1\41\2\10"+
    "\1\71\3\10\1\64\1\10\1\66\2\10\1\43\2\10\1\36\1\0"+
    "\1\37\1\0\1\20\1\0\1\60\1\70\1\72\1\53\1\46\1\45"+
    "\1\65\1\52\1\44\1\76\1\10\1\47\1\74\1\61\1\54\1\75"+
    "\1\10\1\56\1\50\1\55\1\57\1\73\1\51\1\77\1\67\1\10"+
    "\1\34\1\16\1\35\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uff92\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\2\2\1\3\1\4\2\5\1\6\1\7"+
    "\1\10\1\11\2\1\1\12\1\13\1\14\1\15\1\16"+
    "\1\17\1\20\1\21\1\22\1\23\1\24\1\25\1\26"+
    "\1\27\1\30\1\31\1\32\25\6\1\33\2\0\1\34"+
    "\1\35\1\36\1\37\1\40\1\41\1\42\1\43\1\44"+
    "\2\6\1\45\1\46\12\6\1\47\17\6\2\0\1\50"+
    "\1\51\1\52\12\6\1\53\5\6\1\54\1\55\1\6"+
    "\1\56\1\6\1\57\4\6\1\60\1\61\1\0\4\6"+
    "\1\62\2\6\1\63\3\6\1\64\4\6\1\65\2\6"+
    "\1\66\1\6\1\67\1\70\2\6\1\71\3\6\1\72"+
    "\1\6\1\73\1\74\1\75\1\76\2\6\1\77\1\6"+
    "\1\100\3\6\1\101\1\6\1\102\2\6\1\103\1\6"+
    "\1\104\1\6\1\105\1\106\1\107";

  private static int [] zzUnpackAction() {
    int [] result = new int[183];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\100\0\200\0\100\0\300\0\u0100\0\100\0\u0140"+
    "\0\u0180\0\u01c0\0\u0200\0\u0240\0\u0280\0\u02c0\0\u0300\0\100"+
    "\0\100\0\100\0\100\0\u0340\0\u0380\0\u03c0\0\100\0\100"+
    "\0\100\0\100\0\100\0\100\0\100\0\100\0\100\0\u0400"+
    "\0\u0440\0\u0480\0\u04c0\0\u0500\0\u0540\0\u0580\0\u05c0\0\u0600"+
    "\0\u0640\0\u0680\0\u06c0\0\u0700\0\u0740\0\u0780\0\u07c0\0\u0800"+
    "\0\u0840\0\u0880\0\u08c0\0\u0900\0\100\0\u0940\0\u0980\0\100"+
    "\0\100\0\100\0\100\0\100\0\100\0\u09c0\0\100\0\100"+
    "\0\u0a00\0\u0a40\0\u0180\0\u0180\0\u0a80\0\u0ac0\0\u0b00\0\u0b40"+
    "\0\u0b80\0\u0bc0\0\u0c00\0\u0c40\0\u0c80\0\u0cc0\0\u0180\0\u0d00"+
    "\0\u0d40\0\u0d80\0\u0dc0\0\u0e00\0\u0e40\0\u0e80\0\u0ec0\0\u0f00"+
    "\0\u0f40\0\u0f80\0\u0fc0\0\u1000\0\u1040\0\u1080\0\u10c0\0\u1100"+
    "\0\100\0\100\0\u0180\0\u1140\0\u1180\0\u11c0\0\u1200\0\u1240"+
    "\0\u1280\0\u12c0\0\u1300\0\u1340\0\u1380\0\u0180\0\u13c0\0\u1400"+
    "\0\u1440\0\u1480\0\u14c0\0\u1500\0\u0180\0\u1540\0\u0180\0\u1580"+
    "\0\u0180\0\u15c0\0\u1600\0\u1640\0\u1680\0\u0180\0\u0180\0\u16c0"+
    "\0\u1700\0\u1740\0\u1780\0\u17c0\0\u0180\0\u1800\0\u1840\0\u0180"+
    "\0\u1880\0\u18c0\0\u1900\0\u0180\0\u1940\0\u1980\0\u19c0\0\u1a00"+
    "\0\u0180\0\u1a40\0\u1a80\0\u0180\0\u1ac0\0\u0180\0\u0180\0\u1b00"+
    "\0\u1b40\0\u0180\0\u1b80\0\u1bc0\0\u1c00\0\u0180\0\u1c40\0\u0180"+
    "\0\u0180\0\u0180\0\u0180\0\u1c80\0\u1cc0\0\u0180\0\u1d00\0\u0180"+
    "\0\u1d40\0\u1d80\0\u1dc0\0\u0180\0\u1e00\0\u0180\0\u1e40\0\u1e80"+
    "\0\u0180\0\u1ec0\0\u0180\0\u1f00\0\u0180\0\u0180\0\u0180";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[183];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\2\4\1\5\1\6\1\7\1\10\1\11"+
    "\1\2\1\12\1\13\1\14\1\15\1\16\1\17\1\20"+
    "\1\21\1\22\1\23\1\24\1\25\1\26\1\27\1\30"+
    "\1\31\1\32\1\33\1\34\1\35\1\36\1\37\1\40"+
    "\1\11\1\41\1\11\1\42\1\43\1\44\1\45\1\46"+
    "\1\47\1\11\1\50\1\51\1\52\1\53\1\54\1\55"+
    "\1\56\1\57\1\60\1\61\1\11\1\62\3\11\1\63"+
    "\1\64\4\11\102\0\1\4\103\0\1\7\1\10\75\0"+
    "\1\65\1\7\1\10\76\0\2\10\76\0\4\11\6\0"+
    "\1\11\17\0\40\11\12\0\1\66\1\67\76\0\1\70"+
    "\112\0\1\71\67\0\1\72\100\0\1\73\106\0\1\74"+
    "\77\0\1\75\77\0\1\76\1\77\76\0\1\100\60\0"+
    "\4\11\6\0\1\11\17\0\1\11\1\101\14\11\1\102"+
    "\21\11\6\0\4\11\6\0\1\11\17\0\3\11\1\103"+
    "\34\11\6\0\4\11\6\0\1\11\17\0\5\11\1\104"+
    "\13\11\1\105\12\11\1\106\3\11\6\0\4\11\6\0"+
    "\1\11\17\0\20\11\1\107\17\11\6\0\4\11\6\0"+
    "\1\11\17\0\7\11\1\110\11\11\1\111\15\11\1\112"+
    "\6\0\4\11\6\0\1\11\17\0\14\11\1\113\23\11"+
    "\6\0\4\11\6\0\1\11\17\0\17\11\1\114\20\11"+
    "\6\0\4\11\6\0\1\11\17\0\12\11\1\115\25\11"+
    "\6\0\4\11\6\0\1\11\17\0\6\11\1\116\5\11"+
    "\1\117\23\11\6\0\4\11\6\0\1\11\17\0\30\11"+
    "\1\120\7\11\6\0\4\11\6\0\1\11\17\0\16\11"+
    "\1\121\21\11\6\0\4\11\6\0\1\11\17\0\6\11"+
    "\1\122\31\11\6\0\4\11\6\0\1\11\17\0\21\11"+
    "\1\123\16\11\6\0\4\11\6\0\1\11\17\0\32\11"+
    "\1\124\5\11\6\0\4\11\6\0\1\11\17\0\6\11"+
    "\1\125\10\11\1\126\20\11\6\0\4\11\6\0\1\11"+
    "\17\0\21\11\1\127\16\11\6\0\4\11\6\0\1\11"+
    "\17\0\14\11\1\130\23\11\6\0\4\11\6\0\1\11"+
    "\17\0\6\11\1\131\6\11\1\132\22\11\6\0\4\11"+
    "\6\0\1\11\17\0\21\11\1\133\16\11\6\0\4\11"+
    "\6\0\1\11\17\0\7\11\1\134\10\11\1\135\17\11"+
    "\6\0\4\11\6\0\1\11\17\0\20\11\1\136\17\11"+
    "\1\66\1\3\1\4\75\66\13\137\1\140\1\141\63\137"+
    "\25\0\1\142\60\0\4\11\6\0\1\11\17\0\1\11"+
    "\1\143\36\11\6\0\4\11\6\0\1\11\17\0\16\11"+
    "\1\144\21\11\6\0\4\11\6\0\1\11\17\0\15\11"+
    "\1\145\22\11\6\0\4\11\6\0\1\11\17\0\35\11"+
    "\1\146\2\11\6\0\4\11\6\0\1\11\17\0\7\11"+
    "\1\147\30\11\6\0\4\11\6\0\1\11\17\0\10\11"+
    "\1\150\27\11\6\0\4\11\6\0\1\11\17\0\10\11"+
    "\1\151\27\11\6\0\4\11\6\0\1\11\17\0\15\11"+
    "\1\152\22\11\6\0\4\11\6\0\1\11\17\0\14\11"+
    "\1\153\23\11\6\0\4\11\6\0\1\11\17\0\30\11"+
    "\1\154\7\11\6\0\4\11\6\0\1\11\17\0\4\11"+
    "\1\155\33\11\6\0\4\11\6\0\1\11\17\0\5\11"+
    "\1\156\32\11\6\0\4\11\6\0\1\11\17\0\36\11"+
    "\1\157\1\11\6\0\4\11\6\0\1\11\17\0\17\11"+
    "\1\160\20\11\6\0\4\11\6\0\1\11\17\0\20\11"+
    "\1\161\17\11\6\0\4\11\6\0\1\11\17\0\4\11"+
    "\1\162\10\11\1\163\22\11\6\0\4\11\6\0\1\11"+
    "\17\0\15\11\1\164\22\11\6\0\4\11\6\0\1\11"+
    "\17\0\11\11\1\165\26\11\6\0\4\11\6\0\1\11"+
    "\17\0\7\11\1\166\30\11\6\0\4\11\6\0\1\11"+
    "\17\0\15\11\1\167\22\11\6\0\4\11\6\0\1\11"+
    "\17\0\14\11\1\170\23\11\6\0\4\11\6\0\1\11"+
    "\17\0\15\11\1\171\22\11\6\0\4\11\6\0\1\11"+
    "\17\0\16\11\1\172\21\11\6\0\4\11\6\0\1\11"+
    "\17\0\4\11\1\173\33\11\6\0\4\11\6\0\1\11"+
    "\17\0\20\11\1\174\17\11\6\0\4\11\6\0\1\11"+
    "\17\0\10\11\1\175\27\11\6\0\4\11\6\0\1\11"+
    "\17\0\7\11\1\176\6\11\1\177\21\11\13\137\1\200"+
    "\64\137\12\0\1\4\1\140\72\0\4\11\6\0\1\11"+
    "\17\0\20\11\1\201\17\11\6\0\4\11\6\0\1\11"+
    "\17\0\6\11\1\202\31\11\6\0\4\11\6\0\1\11"+
    "\17\0\14\11\1\203\23\11\6\0\4\11\6\0\1\11"+
    "\17\0\10\11\1\204\27\11\6\0\4\11\6\0\1\11"+
    "\17\0\6\11\1\205\31\11\6\0\4\11\6\0\1\11"+
    "\17\0\17\11\1\206\20\11\6\0\4\11\6\0\1\11"+
    "\17\0\6\11\1\207\31\11\6\0\4\11\6\0\1\11"+
    "\17\0\35\11\1\210\2\11\6\0\4\11\6\0\1\11"+
    "\17\0\10\11\1\211\27\11\6\0\4\11\6\0\1\11"+
    "\17\0\7\11\1\212\30\11\6\0\4\11\6\0\1\11"+
    "\17\0\6\11\1\213\31\11\6\0\4\11\6\0\1\11"+
    "\17\0\6\11\1\214\31\11\6\0\4\11\6\0\1\11"+
    "\17\0\32\11\1\215\5\11\6\0\4\11\6\0\1\11"+
    "\17\0\14\11\1\216\23\11\6\0\4\11\6\0\1\11"+
    "\17\0\4\11\1\217\33\11\6\0\4\11\6\0\1\11"+
    "\17\0\14\11\1\220\23\11\6\0\4\11\6\0\1\11"+
    "\17\0\7\11\1\221\30\11\6\0\4\11\6\0\1\11"+
    "\17\0\7\11\1\222\30\11\6\0\4\11\6\0\1\11"+
    "\17\0\4\11\1\223\33\11\6\0\4\11\6\0\1\11"+
    "\17\0\15\11\1\224\22\11\6\0\4\11\6\0\1\11"+
    "\17\0\10\11\1\225\27\11\6\0\4\11\6\0\1\11"+
    "\17\0\6\11\1\226\31\11\12\137\1\4\1\200\64\137"+
    "\6\0\4\11\6\0\1\11\17\0\27\11\1\227\10\11"+
    "\6\0\4\11\6\0\1\11\17\0\16\11\1\230\21\11"+
    "\6\0\4\11\6\0\1\11\17\0\16\11\1\231\21\11"+
    "\6\0\4\11\6\0\1\11\17\0\6\11\1\232\31\11"+
    "\6\0\4\11\6\0\1\11\17\0\16\11\1\233\21\11"+
    "\6\0\4\11\6\0\1\11\17\0\21\11\1\234\16\11"+
    "\6\0\4\11\6\0\1\11\17\0\6\11\1\235\31\11"+
    "\6\0\4\11\6\0\1\11\17\0\6\11\1\236\31\11"+
    "\6\0\4\11\6\0\1\11\17\0\32\11\1\237\5\11"+
    "\6\0\4\11\6\0\1\11\17\0\15\11\1\240\22\11"+
    "\6\0\4\11\6\0\1\11\17\0\21\11\1\241\16\11"+
    "\6\0\4\11\6\0\1\11\17\0\7\11\1\242\30\11"+
    "\6\0\4\11\6\0\1\11\17\0\16\11\1\243\21\11"+
    "\6\0\4\11\6\0\1\11\17\0\6\11\1\244\31\11"+
    "\6\0\4\11\6\0\1\11\17\0\21\11\1\245\16\11"+
    "\6\0\4\11\6\0\1\11\17\0\10\11\1\246\27\11"+
    "\6\0\4\11\6\0\1\11\17\0\10\11\1\247\27\11"+
    "\6\0\4\11\6\0\1\11\17\0\15\11\1\250\22\11"+
    "\6\0\4\11\6\0\1\11\17\0\4\11\1\251\33\11"+
    "\6\0\4\11\6\0\1\11\17\0\13\11\1\252\24\11"+
    "\6\0\4\11\6\0\1\11\17\0\15\11\1\253\22\11"+
    "\6\0\4\11\6\0\1\11\17\0\15\11\1\254\22\11"+
    "\6\0\4\11\6\0\1\11\17\0\20\11\1\255\17\11"+
    "\6\0\4\11\6\0\1\11\17\0\25\11\1\256\12\11"+
    "\6\0\4\11\6\0\1\11\17\0\6\11\1\257\31\11"+
    "\6\0\4\11\6\0\1\11\17\0\21\11\1\260\16\11"+
    "\6\0\4\11\6\0\1\11\17\0\10\11\1\261\27\11"+
    "\6\0\4\11\6\0\1\11\17\0\31\11\1\262\6\11"+
    "\6\0\4\11\6\0\1\11\17\0\21\11\1\263\16\11"+
    "\6\0\4\11\6\0\1\11\17\0\32\11\1\264\5\11"+
    "\6\0\4\11\6\0\1\11\17\0\25\11\1\265\12\11"+
    "\6\0\4\11\6\0\1\11\17\0\5\11\1\266\32\11"+
    "\6\0\4\11\6\0\1\11\17\0\15\11\1\267\22\11";

  private static int [] zzUnpackTrans() {
    int [] result = new int[8000];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\1\1\1\11\2\1\1\11\10\1\4\11"+
    "\3\1\11\11\25\1\1\11\2\0\6\11\1\1\2\11"+
    "\36\1\2\0\2\11\35\1\1\0\67\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[183];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true iff the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true iff the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
    private Symbol symbol(int type) {
        return new Symbol(type, yyline, yycolumn);
    }

    private Symbol symbol(int type, Object value) {
        return new Symbol(type, yyline, yycolumn, value);
    }
    
    public int getLine() { return  yyline; }
    public int getColumn() {return yycolumn; }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 200) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  private final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  private final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  private final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  private final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  private final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  private final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  private final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  private void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          {   return symbol(Symbols.EOF);
 }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { System.err.println("Illegal character '" + yytext() + "'" + " Scala Lexial Analyzer in " + yyline + " " + yycolumn);
            } 
            // fall through
          case 72: break;
          case 2: 
            { /* skip */
            } 
            // fall through
          case 73: break;
          case 3: 
            { return symbol(Symbols.PLUS);
            } 
            // fall through
          case 74: break;
          case 4: 
            { return symbol(Symbols.MINUS);
            } 
            // fall through
          case 75: break;
          case 5: 
            { return symbol(Symbols.NUMBER, new BigInteger(yytext()));
            } 
            // fall through
          case 76: break;
          case 6: 
            { return symbol(Symbols.ID, new String(yytext()));
            } 
            // fall through
          case 77: break;
          case 7: 
            { return symbol(Symbols.DIV);
            } 
            // fall through
          case 78: break;
          case 8: 
            { return symbol(Symbols.TIMES);
            } 
            // fall through
          case 79: break;
          case 9: 
            { return symbol(Symbols.COLON);
            } 
            // fall through
          case 80: break;
          case 10: 
            { return symbol(Symbols.NOT);
            } 
            // fall through
          case 81: break;
          case 11: 
            { return symbol(Symbols.UNDERLINE);
            } 
            // fall through
          case 82: break;
          case 12: 
            { return symbol(Symbols.MOD);
            } 
            // fall through
          case 83: break;
          case 13: 
            { return symbol(Symbols.DOLLAR);
            } 
            // fall through
          case 84: break;
          case 14: 
            { return symbol(Symbols.ATSIGN);
            } 
            // fall through
          case 85: break;
          case 15: 
            { return symbol(Symbols.LT);
            } 
            // fall through
          case 86: break;
          case 16: 
            { return symbol(Symbols.EQ);
            } 
            // fall through
          case 87: break;
          case 17: 
            { return symbol(Symbols.GT);
            } 
            // fall through
          case 88: break;
          case 18: 
            { return symbol(Symbols.DOT);
            } 
            // fall through
          case 89: break;
          case 19: 
            { return symbol(Symbols.COMMA);
            } 
            // fall through
          case 90: break;
          case 20: 
            { return symbol(Symbols.SEMICOLON);
            } 
            // fall through
          case 91: break;
          case 21: 
            { return symbol(Symbols.LPAREN);
            } 
            // fall through
          case 92: break;
          case 22: 
            { return symbol(Symbols.RPAREN);
            } 
            // fall through
          case 93: break;
          case 23: 
            { return symbol(Symbols.LCURLYBRACKET);
            } 
            // fall through
          case 94: break;
          case 24: 
            { return symbol(Symbols.RCURLYBRACKET);
            } 
            // fall through
          case 95: break;
          case 25: 
            { return symbol(Symbols.LSQUAREBRACKET);
            } 
            // fall through
          case 96: break;
          case 26: 
            { return symbol(Symbols.RSQUAREBRACKET);
            } 
            // fall through
          case 97: break;
          case 27: 
            { return symbol(Symbols.MINUSMINUS);
            } 
            // fall through
          case 98: break;
          case 28: 
            { return symbol(Symbols.RANNOT);
            } 
            // fall through
          case 99: break;
          case 29: 
            { return symbol(Symbols.COLEQ);
            } 
            // fall through
          case 100: break;
          case 30: 
            { return symbol(Symbols.AND);
            } 
            // fall through
          case 101: break;
          case 31: 
            { return symbol(Symbols.OR);
            } 
            // fall through
          case 102: break;
          case 32: 
            { return symbol(Symbols.NEQ);
            } 
            // fall through
          case 103: break;
          case 33: 
            { return symbol(Symbols.LEQ);
            } 
            // fall through
          case 104: break;
          case 34: 
            { return symbol(Symbols.EQEQ);
            } 
            // fall through
          case 105: break;
          case 35: 
            { return symbol(Symbols.DOUBLEARROW);
            } 
            // fall through
          case 106: break;
          case 36: 
            { return symbol(Symbols.GEQ);
            } 
            // fall through
          case 107: break;
          case 37: 
            { return symbol(Symbols.EX);
            } 
            // fall through
          case 108: break;
          case 38: 
            { return symbol(Symbols.IF);
            } 
            // fall through
          case 109: break;
          case 39: 
            { return symbol(Symbols.DO);
            } 
            // fall through
          case 110: break;
          case 40: 
            { return symbol(Symbols.LANNOT);
            } 
            // fall through
          case 111: break;
          case 41: 
            { return symbol(Symbols.EQEQEQ);
            } 
            // fall through
          case 112: break;
          case 42: 
            { return symbol(Symbols.ALL);
            } 
            // fall through
          case 113: break;
          case 43: 
            { return symbol(Symbols.DEF);
            } 
            // fall through
          case 114: break;
          case 44: 
            { return symbol(Symbols.ACT);
            } 
            // fall through
          case 115: break;
          case 45: 
            { return symbol(Symbols.NEW);
            } 
            // fall through
          case 116: break;
          case 46: 
            { return symbol(Symbols.INT);
            } 
            // fall through
          case 117: break;
          case 47: 
            { return symbol(Symbols.SET);
            } 
            // fall through
          case 118: break;
          case 48: 
            { return symbol(Symbols.VAL);
            } 
            // fall through
          case 119: break;
          case 49: 
            { return symbol(Symbols.VAR);
            } 
            // fall through
          case 120: break;
          case 50: 
            { return symbol(Symbols.ELSE);
            } 
            // fall through
          case 121: break;
          case 51: 
            { return symbol(Symbols.LOOP);
            } 
            // fall through
          case 122: break;
          case 52: 
            { return symbol(Symbols.TRUE);
            } 
            // fall through
          case 123: break;
          case 53: 
            { return symbol(Symbols.NULL);
            } 
            // fall through
          case 124: break;
          case 54: 
            { return symbol(Symbols.UNIT);
            } 
            // fall through
          case 125: break;
          case 55: 
            { return symbol(Symbols.CASE);
            } 
            // fall through
          case 126: break;
          case 56: 
            { return symbol(Symbols.ARRAY);
            } 
            // fall through
          case 127: break;
          case 57: 
            { return symbol(Symbols.FALSE);
            } 
            // fall through
          case 128: break;
          case 58: 
            { return symbol(Symbols.WHILE);
            } 
            // fall through
          case 129: break;
          case 59: 
            { return symbol(Symbols.REACT);
            } 
            // fall through
          case 130: break;
          case 60: 
            { return symbol(Symbols.UNION);
            } 
            // fall through
          case 131: break;
          case 61: 
            { return symbol(Symbols.UNTIL);
            } 
            // fall through
          case 132: break;
          case 62: 
            { return symbol(Symbols.ACTOR);
            } 
            // fall through
          case 133: break;
          case 63: 
            { return symbol(Symbols.CLASS);
            } 
            // fall through
          case 134: break;
          case 64: 
            { return symbol(Symbols.IMPORT);
            } 
            // fall through
          case 135: break;
          case 65: 
            { return symbol(Symbols.OBJECT);
            } 
            // fall through
          case 136: break;
          case 66: 
            { return symbol(Symbols.STRING);
            } 
            // fall through
          case 137: break;
          case 67: 
            { return symbol(Symbols.EXTENDS);
            } 
            // fall through
          case 138: break;
          case 68: 
            { return symbol(Symbols.BOOLEAN);
            } 
            // fall through
          case 139: break;
          case 69: 
            { return symbol(Symbols.ENSURING);
            } 
            // fall through
          case 140: break;
          case 70: 
            { return symbol(Symbols.SUBSETOF);
            } 
            // fall through
          case 141: break;
          case 71: 
            { return symbol(Symbols.INTERSECT);
            } 
            // fall through
          case 142: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
